@hostname = localhost:10411


### 주문 생성 (회원)
POST http://{{hostname}}/api/orders
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: MEMBER

{
  "ordererName": "홍길동",
  "ordererContact": "010-1234-5678",
  "deliveryDate": "2024-07-15T10:00:00",

  "receiverName": "김철수",
  "receiverContact": "010-9876-5432",
  "receiverAddress": "광주광역시 동구 제봉로 92 (대성학원)",
  "receiverPostCode": "61455",

  "nonMemberPassword": null,

  "pointUsage": 1000,
  "orderItems": [
    {
      "bookId": 1,
      "quantity": 2,
      "couponId": 1,
      "packagingId": 2
    },
    {
      "bookId": 2,
      "quantity": 2,
      "couponId": null,
      "packagingId": 1
    }
  ]
}

### 주문 생성 (비회원)
POST http://{{hostname}}/api/orders
Content-Type: application/json

{
  "ordererName": "이영희",
  "ordererContact": "010-2222-3333",
  "deliveryDate": "2024-07-15T14:00:00",

  "receiverName": "박민수",
  "receiverContact": "010-4444-5555",
  "receiverAddress": "서울특별시 강남구 테헤란로 123 (삼성동)",
  "receiverPostCode": "06134",

  "nonMemberPassword": "nonmemberpass",

  "pointUsage": 0,
  "orderItems": [
    {
      "bookId": 3,
      "quantity": 1,
      "couponId": null,
      "packagingId": 3
    }
  ]
}

### 주문 목록 조회 (관리자)
GET http://{{hostname}}/api/orders/admin
X-USER-ID: 2
X-USER-ROLE: ADMIN

### 주문 목록 조회 (회원)
GET http://{{hostname}}/api/orders
X-USER-ID: 1
X-USER-ROLE: MEMBER

### 주문 단건 조회 (회원)
GET http://{{hostname}}/api/orders/1
X-USER-ID: 1
X-USER-ROLE: MEMBER

### 주문 단건 조회 (비회원)
POST http://{{hostname}}/api/orders/non-members/
Content-Type: application/json

{
  "orderNumber": "ORD-3a6e29ec-f84c-491d-a13e-8aeeb90ffa58",
  "nonMemberPassword": "nonmemberpass"
}

### 주문 상품 상태 변경: 주문 취소 (회원)
PATCH http://{{hostname}}/api/orders/1/items/1
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: MEMBER

{
  "status": "CANCELED"
}

### 주문 상품 상태 변경: 반품 요청 (단순 변심) (회원)
PATCH http://{{hostname}}/api/orders/1/items/1
Content-Type: application/json

{
  "status": "RETURN_REQUESTED_CHANGE_OF_MIND"
}

### 주문 상품 상태 변경: 반품 완료 (회원)
PATCH http://{{hostname}}/api/orders/1/items/1
Content-Type: application/json

{
  "status": "RETURNED"
}

### 주문 상품 상태 변경: 구매 확정 (회원)
PATCH http://{{hostname}}/api/orders/1/items/1
Content-Type: application/json

{
  "status": "CONFIRMED"
}

### 주문 상품 상태 변경: 주문 취소 (비회원)
PATCH http://{{hostname}}/api/orders/non-members/1/items/1
Content-Type: application/json

{
  "nonMemberPassword": "nonmemberpass",
  "status": "CANCELED"
}
