#
# /*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + Copyright 2025. NHN Academy Corp. All rights reserved.
# + * While every precaution has been taken in the preparation of this resource,  assumes no
# + responsibility for errors or omissions, or for damages resulting from the use of the information
# + contained herein
# + No part of this resource may be reproduced, stored in a retrieval system, or transmitted, in any
# + form or by any means, electronic, mechanical, photocopying, recording, or otherwise, without the
# + prior written permission.
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
#

spring.application.name=ORDER-SERVICE

# ?????? ? JPA ??
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=test
spring.datasource.password=1234
spring.datasource.dbcp2.connection-init-sqls=SELECT 1

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.auto_quote_keyword=true

server.port=10411

# ??? ??? Order? ?? ?? ??
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

logging.level.org.hibernate.type=trace


##Eureka ????? ??
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address= true
eureka.instance.instance-id=${spring.application.name}:${server.port}


##Actuator ? Logging
management.endpoints.web.exposure.include=health, info
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.transaction.interceptor=trace
logging.level.com.nhnacademy.OrderApplication= DEBUG


toss.secret-key=test_sk_XZYkKL4Mrj10Wz7kA0EBV0zJwlEW