server:
  port: 10407
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: order-service
  # 장바구니 서비스는 보통 Redis를 필수적으로 사용 (TTL 기능 등)
  data:
    redis:
      host: localhost
      port: 6379

  # JPA, Datasource, H2 설정
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: 1234
    driver-class-name: org.h2.Driver
    dbcp2:
      connection-init-sqls: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        # Order Setting
        globally_quoted_identifiers: true

  # Cloud 설정
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

# Resilience4j 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        # 최근 요청 중 50% 이상 실패하면 서킷을 엶(Open)
        failure-rate-threshold: 50
        # 시간(Time)이 아닌 횟수(Count) 기준으로 실패율 계산
        sliding-window-type: count-based
        # 10개의 요청 결과를 보고 실패율 계산 (테스트용)
        sliding-window-size: 10
        # 서킷이 열리면 10초 동안은 무조건 차단 (바로 CallNotPermittedException 발생시킴)
        wait-duration-in-open-state:
          seconds: 10
        # 10초가 지나면 반-열림(Half-Open) 상태로 전환
        automatic-transition-from-open-to-half-open-enabled: true
        # 반-열림 상태에서 받을 요청의 개수 (해당 요청들 중 하나라도 실패하면 서킷을 다시 열고, 모두 통과하면 닫음)
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      book-service: {}
      coupon-service: {}
      member-service: {}

  retry:
    configs:
      default:
        # 최대 시도 횟수 (최초 시도 1회, 재시도 2회)
        max-attempts: 3
        # 대기 시간 1초
        wait-duration:
          seconds: 1
        # 재시도 대상 예외
        retry-exceptions:
          # 네트워크 연결 실패, 일시적 장애
          - feign.RetryableException
          # 응답이 너무 늦는 경우
          - java.util.concurrent.TimeoutException
    instances:
      book-service: {}
      coupon-service: {}
      member-service: {}

# 환경 변수 설정
# 기존: secret-key: ${TOSS_KEY}
# 변경: 콜론(:) 뒤에 임시 값을 적어주면 환경변수가 없을 때 이 값을 씁니다
toss:
  secret-key: ${TOSS_KEY:test_secret_key_1234}